language: ruby
rvm:
  - 1.9.3

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_install:
  # Install PostGIS 2.0
  - sudo apt-add-repository ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -qq libgeos-dev libproj-dev postgresql-9.1-postgis
  - sudo apt-get install -qq libgeos++-dev

before_script:
  - cp config/database.travis.yml config/database.yml

  # Create PostGIS extension
  - createdb -U postgres trans_resource_finder_test
  - psql -U postgres -d trans_resource_finder_test -c "CREATE EXTENSION postgis;"

deploy:
  provider: heroku
  api_key:
    secure: LWiNHgauTcWXOvh1hFc04OwB7aKw+qLqpZh0Vmc5FjqB9KPHMf1RX6BDckz/8QcoD9KdofuQtgaLWrRnk/rKxGpz5RtXhosua/WkV6jPG6GAcQn43cHOHG1QzPah0lvf1qOeHZUUotDRBCOhXsAGOq9Kyrq9QF2opcqDYTMJGFg=
  app: trans-resource-finder
  run: "rake db:migrate"
  on:
    repo: Trans-H4CK/trans_resource_finder
    rvm: 1.9.3