postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  database: trans_resource_finder_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults